### ISSUE TITLE
Test the repo documentation

### ISSUE THREAD

**Issue by paolo-viceconte** [ami-iit/paper_viceconte_2021_ral_adherent#1]
This issue is to check the documentation of this repo, in order to understand whether the procedure to run the code is complete and clear enough.

**Comment by MarcoCaianiello** [comment]
I have tested all the procedure and it works fine!

**Comment by paolo-viceconte** [comment]
Thanks a lot @MarcoCaianiello for the testing! 

Just to add some context, the test was conducted on Ubuntu 20.04, with no docker nor docker-compose installed before starting the procedure. So it was a real test from the very beginning of the setup configuration.

As expected, by following [section 5](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#5-interactive-trajectory-generation), @MarcoCaianiello managed to interactively generate a new trajectory including forward, sideways and backward walking that was then successfully controlled in simulation by following [section 6](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#6-trajectory-control-in-simulation).

**Comment by paolo-viceconte** [comment]
I edited some sections of the wikies for the [setup configuration](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-setup-configuration) and the [scripts execution](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution) by integrating the suggestions on how to improve the clarity of the documentation, provided by @MarcoCaianiello while testing.

An open point remains on the possibility to add videos in the documentation showing an example of interactive trajectory generation at the beginning of [section 5](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#5-interactive-trajectory-generation) and an example of trajectory control in simulation at the beginning of [section 6](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#6-trajectory-control-in-simulation).

**Comment by paolo-viceconte** [comment]
> An open point remains on the possibility to add videos in the documentation showing an example of interactive trajectory generation at the beginning of [section 5](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#5-interactive-trajectory-generation) and an example of trajectory control in simulation at the beginning of [section 6](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#6-trajectory-control-in-simulation).

Apparently videos cannot be directly added to wikis, which is where the repo documentation is stored. I will add the videos in separate comments below and link them in the wiki.

**Comment by paolo-viceconte** [comment]
> An open point remains on the possibility to add videos in the documentation showing an example of interactive trajectory generation at the beginning of [section 5](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#5-interactive-trajectory-generation) and an example of trajectory control in simulation at the beginning of [section 6](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#6-trajectory-control-in-simulation).

Example videos added at the beginning of [section 5](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#5-interactive-trajectory-generation) and [section 6](https://github.com/ami-iit/paper_viceconte_2021_ral_adherent/wiki/ADHERENT-scripts-execution#6-trajectory-control-in-simulation). The videos are not directly rendered in the wiki but they can be visualized in a different page by clicking on the associated link, which leaves the wiki even cleaner. Closing this issue.
